services:
  hearthandkin:
    restart: always
    container_name: hearthandkin
    image: sjoeborg/hearthandkin:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: .
        target: /app/
    ports:
      - 8000:8000
    env_file:
      - .env