[tool.poetry]
name = "hearth-and-kin"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.0"
setuptools = "^69.0.2"
bcrypt = "^4.1.1"
elevenlabs = "0.2.24"
openai = "^1.3.6"
flask = "^3.0.0"
flask-sqlalchemy = "^3.1.1"
flask-socketio = "^5.3.6"
python-dotenv = "^1.0.0"
pillow = "^10.1.0"
pytest = "^7.4.3"
langchain = "^0.0.343"
fastapi = "^0.104.1"
uvicorn = "^0.24.0.post1"
python-socketio = "^5.10.0"
sqlmodel = "^0.0.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
