[tool.poetry]
name = "hearth-and-kin"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "hearth_and_kin"}]

[tool.poetry.dependencies]
python = "3.12.0"
setuptools = "^69.0.2"
bcrypt = "^4.1.1"
elevenlabs = "^0.2.26"
openai = "^1.3.6"
flask = "^3.0.0"
flask-sqlalchemy = "^3.1.1"
flask-socketio = "^5.3.6"
python-dotenv = "^1.0.0"
pillow = "^10.1.0"
pytest = "^7.4.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
